[package]
name = "server"
version = "0.1.0"
edition = "2024"

[lints.rust]

[dependencies]
anyhow = "1.0.100"
axum = { version = "0.8.8", features = ["macros"] }
clap = { version = "4.5.54", features = ["derive"] }
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_valid = "2.0.1"
tokio = { version = "1.49.0", features = ["full"] }
tower-http = { version = "0.6.8", features = ["catch-panic"] }
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio", "chrono"] }
chrono = { version = "0.4.43", features = ["serde"] }
zip = "7.1.0"
# v0.15.3 does not work on
indicatif = { version = "0.18.3" }
lzma-rust2 = "0.15.7"
console = "0.16.2"
rayon = "1.11.0"
validator = { version = "0.20.0", features = ["derive"] }
axum-extra = { version = "0.12.5", features = ["with-rejection"] }
vibrato = "0.5.2"
zstd = "0.13.3"
